# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de1dd9d00953d659de87422d91bff873effda3a1a9c2963c709ee1902151242f55e1d721de2b6e9b3bfc1dcad262a82d8751a7d9f366250ee6b75eb72ce8e0c8

test:
  secret_key_base: 10f0756f12bc0f64e592f5dc2fbae7da2dd98e1d9467b27d58125a13ac61d631346baee2a7792d14908bb31e2dcca633109a33f4eccb4d70a4bc0f3859dcab03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
